In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder ## don't use the ohe when there are multiple category

In [2]:
## create a simple dataframe

df=pd.DataFrame({'color':['red','blue','green','green','red','blue']})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [4]:
## create an instance of one hot encoder
encoder=OneHotEncoder()

In [8]:
## perform fit and transform 
encoder.fit_transform(df[['color']]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [9]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [10]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [ ]:
## for new data
encoder.transform([['blue']]).toarray()

c:\Users\preet\anaconda3\envs\practise_env\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [14]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [30]:
import seaborn as sns
df=sns.load_dataset('tips')
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [28]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [32]:
encoded=encoder.fit_transform(df[['sex','smoker','day']]).toarray()

In [33]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [34]:
encoder_df

     sex_Female  sex_Male  smoker_No  ...  day_Sat  day_Sun  day_Thur
0           1.0       0.0        1.0  ...      0.0      1.0       0.0
1           0.0       1.0        1.0  ...      0.0      1.0       0.0
2           0.0       1.0        1.0  ...      0.0      1.0       0.0
3           0.0       1.0        1.0  ...      0.0      1.0       0.0
4           1.0       0.0        1.0  ...      0.0      1.0       0.0
..          ...       ...        ...  ...      ...      ...       ...
239         0.0       1.0        1.0  ...      1.0      0.0       0.0
240         1.0       0.0        0.0  ...      1.0      0.0       0.0
241         0.0       1.0        0.0  ...      1.0      0.0       0.0
242         0.0       1.0        1.0  ...      1.0      0.0       0.0
243         1.0       0.0        1.0  ...      0.0      0.0       1.0

[244 rows x 8 columns]

In [35]:
df_dropped=df.drop(['sex','smoker','day'],axis=1)

In [37]:
final_df=pd.concat([df_dropped,encoder_df],axis=1)

print(final_df.head())

   total_bill   tip    time  size  ...  day_Fri  day_Sat  day_Sun  day_Thur
0       16.99  1.01  Dinner     2  ...      0.0      0.0      1.0       0.0
1       10.34  1.66  Dinner     3  ...      0.0      0.0      1.0       0.0
2       21.01  3.50  Dinner     3  ...      0.0      0.0      1.0       0.0
3       23.68  3.31  Dinner     2  ...      0.0      0.0      1.0       0.0
4       24.59  3.61  Dinner     4  ...      0.0      0.0      1.0       0.0

[5 rows x 12 columns]